### PR TITLE
working design changes for ticket checkout flow

### PR DESCRIPTION
**Pull request by Aslan1st**
@mprunell I want to bring up that there is a bug when checking out with a signed in user who does not have a name. The reservation name will not be displayed as expected on the order overview page. I have it working correctly on the thank you page. Maybe take a look and let me know where that info should be coming from. 

Also, can you send me info about the last 4 digits?

### CODE REVIEW

**Comment by mprunell** [comment]
Hey Aslan,

Go to 'preview_mezzrow.html' and do this:

{% with bankcard_form.bankcard.number as n %}
  <p tabindex="0" >{{ n.12 }}{{ n.13 }}{{ n.14 }}{{ n.15 }}</p>
{% endwith %}

That should take care of it.

Martin

**Comment by Aslan1st** [comment]
@mprunell good to go

**Comment by mprunell** [comment]
Hey Aslan, would you like to fix the reservation names as well?

if ticket_name:
    reservation_string = '{} {}'.format(ticket_name['first'],
ticket_name['last'])
return self.render_preview(self.request,
                           bankcard_form=bankcard_form,
                           payment_method=payment_method,
                           reservation_string=reservation_string)


That code needs to go in handle_payment_details_submission_for_tickets
. That will pass the reservation string.


Martin

**Comment by Aslan1st** [comment]
I'll take care of it.


Sent from iCloud

On August 7, 2019 at 2:44 PM, Martin Prunell <notifications@github.com> wrote:


Hey Aslan, would you like to fix the reservation names as well?

if ticket_name:
reservation_string = '{} {}'.format(ticket_name['first'],
ticket_name['last'])
return self.render_preview(self.request,
bankcard_form=bankcard_form,
payment_method=payment_method,
reservation_string=reservation_string)


That code needs to go in handle_payment_details_submission_for_tickets
. That will pass the reservation string.


Martin

**Comment by Aslan1st** [comment]
@mprunell I had issues implementing the code as written and realized I could get the variables by calling ticket_name.first and ticket_name.last

**Pull request merged**
