### PR TITLE
Jim dev

### PR DESCRIPTION
**Pull request by jamessam**
Closed old pull request, added SVGs, opened new pull request.

For the bullets, I used the arrow image already in the project because (please stop me if I'm wrong), CSS can't do hollow squares. Is there an image of the hollow square that's supposed to be used?

In general, I tried to keep with the style of the existing code.

### CODE REVIEW

**Comment by grozdanowski** [comment]
Hey @jamessam, everything looks good. However, I'd recommend moving icons into a separate subfolder, just so we keep things tidy.

**Comment by natea** [comment]
@grozdanowski now that @jamessam has moved the SVG files into their own directory, could you take another pass at the PR, and if it looks okay, merge it?

**Comment by bezidejni** [comment]
Hey @jamessam , we're currently in the process of setting up a staging server where the code will be deployed, will let you know once it's up and we review everything.

**Comment by bezidejni** [comment]
@natea @grozdanowski @jamessam If you click the "View deployment" button above, you'll see the code deployed to the "staging" heroku server. I say "staging" because I've set it up so that any future pull requests on GitHub automatically create a separate staging app only for that branch/PR that's independent of the actual staging server that's currently set to auto deploy code from the develop branch.

@jamessam , Matej and I will take a look at the changes tomorrow and leave our comments here. Sorry for the delay, setting up the whole deploy pipeline took some more time than was initially planned.

**Comment by natea** [comment]
@bezidejni that's a really cool feature! -> branch specific deployments.

I'm going to send Spike this URL and ask him to look at the sign up page to see if it's as he would like it.

I'm also not sure if he wants the Upgrade button going to the /accounts/upgrade-plan/basic/ page or the http://smallslive-staging-pr-4.herokuapp.com/accounts/subscription-settings/ page where you could optionally select a bigger plan (benefactor or institutional).

@jamessam I'm guessing that Spike will want it going to the /subscription-settings/ page where the member can see which plan they're currently on, and select any plan (including downgrading). we'll need to make this page also match the new look-n-feel of the /accounts/signup/ page.

**Comment by natea** [comment]
@jamessam I think Spike also wanted the "Benefactor levels" on the signup page to be a dropdown menu, and the user could select among 3 different benefactor plans ($1,000/yr, $2,500/yr or $5,000/yr). We need to make corresponding plans on the Stripe side, but we could at least get started on the frontend UI part and wire up the backend once we have those plans defined.

**Comment by grozdanowski** [comment]
@jamessam did you check how the signup page reflows on various screen sizes? I just tried it on mobile (iPhone 6) size and the layout breaks pretty badly. The boxes widen beyond full screen width invoking horizontal scroll. You need to set media queries in sass to:

- limit the max width so it doesn't overflow from screen
- reduce the font size of plan names because they currently create issues for being too large on small screens
- reflow the layout of the plan so the plan button goes below description

**Comment by jamessam** [comment]
Good point. I tweaked things a little to stop the formatting issues in the headings and the buttons. Not ideal, but I wanted to fix this gross error ASAP to at least a reasonable presentation. See my longer comments on Slack.

**Comment by grozdanowski** [comment]
@jamessam the plans reflow correctly now from what I can see.

**Comment by natea** [comment]
@bezidejni did you figure out from Heroku why the pushes aren't getting deployed to the staging server? when do you expect that it will be fixed? I'd like to send an update to Spike so he can see the progress. thanks!

**Comment by natea** [comment]
@bezidejni when i try to view the latest deployment on staging, i get a "Bad Request (400)” error
https://smallslive-staging-pr-4.herokuapp.com/

according to the build log, the build was successful: https://dashboard.heroku.com/apps/smallslive-staging-pr-4/activity/builds/6fbfd970-7a9d-40e5-a7bd-79a34e9fcfa4

Any ideas why we'd be getting this Bad Request (400) error?

**Comment by natea** [comment]
sign_up_complete_-_smallslive

**Pull request merged**
